import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import "./globals.css";
import { NotificationContextProvider } from "@/store/notification-context";
import NotificationContainer from "@/components/ui/notification-container";
import AuthProvider from "@/providers/SessionProvider";
import { CartContextProvider } from "@/store/cart-context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<AuthProvider>
  <NotificationContextProvider>
    <CartContextProvider> 
       <Header />
       {children}
           <NotificationContainer />
    </CartContextProvider>
  </NotificationContextProvider>
</AuthProvider>
      </body>
    </html>
  );
}
